Repository INU-IDLE/client, pull requests merged in 2025-05, with the labels that each got.

#44 Feat: 노선도 id 오류 해결
  .idea/workspace.xml
  lib/data/station_data.dart
  lib/main.dart
  lib/screen/home_screen.dart
  lib/screen/real_time_screen.dart
  lib/screen/search_screen.dart
  lib/screen/subway_map_screen.dart
  lib/widgets/station_component.dart
Labels: 🐞 BugFix

#47 Delete .env
  .env
Labels: 🚨 HotFix

#52 Feat: 도착 정보, 실시간 혼잡도 구현
  assets/images/metropolitan.png
  lib/data/line_mapping.dart
  lib/data/station_data.dart
  lib/main.dart
  lib/models/congestion_data.dart
  lib/models/station.dart
  lib/models/train_arrival.dart
  lib/providers/station_provider.dart
  lib/screen/bottom_category_bar.dart
  lib/screen/congestion_prediction_screen.dart
  lib/screen/home_screen.dart
  lib/screen/real_time_bottom_sheet.dart
  lib/screen/route_result_screen.dart
  lib/screen/subway_map_screen.dart
  lib/services/api_service.dart
  lib/services/api_station_service.dart
  lib/services/station_service.dart
Labels: ✨ Feature, 📬 API
